# Generated by Django 6.0.1 on 2026-05-05 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_role"),
        ("bookclub", "0002_book_available_to_borrow_book_contributor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookreview",
            name="anon_reviwer",
        ),
        migrations.AddField(
            model_name="bookreview",
            name="anon_reviewer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="bookclub.book",
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="date_bookmarked",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="bookreview",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="bookclub.book",
            ),
        ),
        migrations.AlterField(
            model_name="bookreview",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="bookreview",
            name="user_reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="borrow",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrows",
                to="bookclub.book",
            ),
        ),
        migrations.AlterField(
            model_name="borrow",
            name="borrower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="borrow",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
