# Generated by Django 6.0.1 on 2026-05-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0002_commission_maker_commission_status_job_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": [
                    models.Case(
                        models.When(status="Open", then=models.Value(1)),
                        models.When(status="Full", then=models.Value(2)),
                        output_field=models.IntegerField(),
                    ),
                    "-manpower_required",
                    "role",
                ],
                "verbose_name": "job",
                "verbose_name_plural": "jobs",
            },
        ),
        migrations.AlterModelOptions(
            name="jobapplication",
            options={
                "ordering": [
                    models.Case(
                        models.When(status="Pending", then=models.Value(1)),
                        models.When(status="Accepted", then=models.Value(2)),
                        models.When(status="Rejected", then=models.Value(3)),
                        output_field=models.IntegerField(),
                    ),
                    "-applied_on",
                ],
                "verbose_name": "job application",
                "verbose_name_plural": "job applications",
            },
        ),
        migrations.AlterField(
            model_name="commission",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Full", "Full"),
                    ("Completed", "Completed"),
                    ("Discontinued", "Discontinued"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
    ]
