# Generated by Django 6.0.2 on 2026-04-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('commission_maker', 'Commission Maker'), ('regular_user', 'Regular User')], default='regular_user', max_length=50),
        ),
    ]
