# Generated by Django 6.0.1 on 2026-04-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Normal", "Normal"),
                    ("Market Seller", "Market Seller"),
                    ("Event Organizer", "Event Organizer"),
                    ("Book Contributor", "Book Contributor"),
                    ("Project Creator", "Project Creator"),
                    ("Commission Maker", "Commission Maker"),
                ],
                default="Normal",
                max_length=20,
            ),
        ),
    ]
