# Generated by Django 6.0.1 on 2026-04-02 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diyprojects",
         "0003_project_creator_favorite_projectrating_projectreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectrating",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_ratings",
                to="diyprojects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectreview",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_reviews",
                to="diyprojects.project",
            ),
            preserve_default=False,
        ),
    ]
