# Generated by Django 6.0.1 on 2026-04-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diyprojects", "0004_projectrating_project_projectreview_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectreview",
            name="image",
            field=models.ImageField(blank=True,
                                    null=True,
                                    upload_to="images/"),
        ),
    ]
