# Generated by Django 6.0.1 on 2026-04-02 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diyprojects", "0005_alter_projectreview_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectrating",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_ratings",
                to="diyprojects.project",
            ),
        ),
    ]
